# Используйте официальный образ Node.js
FROM node:14

# Установите рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируйте файлы пакетов в контейнер
COPY package*.json./

# Установите зависимости
RUN npm install

# Копируйте исходный код приложения в контейнер
COPY package*.json./

# Соберите приложение
RUN npm run build

# Запустите приложение
CMD ["npm", "run", "start:prod"]